### ISSUE TITLE
error reoccuring

### ISSUE THREAD

**Issue by Arvindgoa1996** [senbox-org/snap-desktop#32] opened 2017-02-06 04:41 UTC
A org.esa.snap.core.gpf.OperatorException exception has occurred 

this error is occurring as the calibration dataet isn't constructing.
whats the cause?

**Comment by marpet** [comment] 2017-02-06 07:51
You should see more information. Please have a look in the details or go to the menu _Help / Show Log Directory_. In the _messages.log_ file you should see more information what's the cause of the exception.
You can also attach it here, so that we ca have a look.

**Comment by Arvindgoa1996** [comment] 2017-02-06 14:29
[messages.txt](https://github.com/senbox-org/snap-desktop/files/754860/messages.txt)

**Comment by marpet** [comment] 2017-02-06 15:25
Sorry, I haven't said that you should run the process which causes the exception before attaching the file.
In the current file I can not see anything.

**Comment by marpet** [comment] 2019-01-29 15:34
We are closing the issues in GitHub in favour of discussing them in the [SNAP Forum](https://forum.step.esa.int) and having the tickets in [JIRA](https://senbox.atlassian.net).
So please ask again in the forum if you have further questions.

**Closed by marpet** 2019-01-29 15:34 UTC
